const links = [
    // {
    //     nRota: 1,
    //     facil1: 'https://mineurl.com/714133',
    //     medio1: 'https://mineurl.com/9f1280',
    //     dificil1: 'https://mineurl.com/08ac01',
    //     facil2: 'https://mineurl.com/83a9f1',
    //     medio2: 'https://mineurl.com/a81d43',
    //     dificil2: 'https://mineurl.com/af4996',
    //     facil3: 'https://mineurl.com/c11bfb',
    //     medio3: 'https://mineurl.com/69c589',
    //     dificil3: 'https://mineurl.com/8b7848'
    // },
    // {
    //     nRota: 2,
    //     facil1: 'https://mineurl.com/ee3664',
    //     medio1: 'https://mineurl.com/049e57',
    //     dificil1: 'https://mineurl.com/c281e1',
    //     facil2: 'https://mineurl.com/57ff56',
    //     medio2: 'https://mineurl.com/cfc392',
    //     dificil2: 'https://mineurl.com/f53331',
    //     facil3: 'https://mineurl.com/466ed5',
    //     medio3: 'https://mineurl.com/d075da',
    //     dificil3: 'https://mineurl.com/131723'
    // },
    // {
    //     nRota: 3,
    //     facil1: 'https://mineurl.com/f775b9',
    //     medio1: 'https://mineurl.com/6df712',
    //     dificil1: 'https://mineurl.com/6c8382',
    //     facil2: 'https://mineurl.com/5aa9b2',
    //     medio2: 'https://mineurl.com/9fb54b',
    //     dificil2: 'https://mineurl.com/c1b074',
    //     facil3: 'https://mineurl.com/bed67a',
    //     medio3: 'https://mineurl.com/db04cc',
    //     dificil3: 'https://mineurl.com/dee5df'
    // },
    // {
    //     nRota: 4,
    //     facil1: 'https://mineurl.com/3db3d0',
    //     medio1: 'https://mineurl.com/ab7903',
    //     dificil1: 'https://mineurl.com/2ca751',
    //     facil2: 'https://mineurl.com/992c98',
    //     medio2: 'https://mineurl.com/cc7a42',
    //     dificil2: 'https://mineurl.com/a73bd2',
    //     facil3: 'https://mineurl.com/3bea67',
    //     medio3: 'https://mineurl.com/2df0bb',
    //     dificil3: 'https://mineurl.com/33ee9d'
    // },
    // {
    //     nRota: 5,
    //     facil1: 'https://mineurl.com/b6573b',
    //     medio1: 'https://mineurl.com/55c5b6',
    //     dificil1: 'https://mineurl.com/e482af',
    //     facil2: 'https://mineurl.com/99d4de',
    //     medio2: 'https://mineurl.com/55c5b6',
    //     dificil2: 'https://mineurl.com/5b868d',
    //     facil3: 'https://mineurl.com/f60428',
    //     medio3: 'https://mineurl.com/97670a',
    //     dificil3: 'https://mineurl.com/ce3540'
    // },
    // {
    //     nRota: 6,
    //     facil1: 'https://mineurl.com/194b74',
    //     medio1: 'https://mineurl.com/b8ad93',
    //     dificil1: 'https://mineurl.com/ca04b4',
    //     facil2: 'https://mineurl.com/b8ad93',
    //     medio2: 'https://mineurl.com/12e713',
    //     dificil2: 'https://mineurl.com/34f4e7',
    //     facil3: 'https://mineurl.com/1053bc',
    //     medio3: 'https://mineurl.com/fb4b0b',
    //     dificil3: 'https://mineurl.com/3edee5'
    // },
    // {
    //     nRota: 7,
    //     facil1: 'https://mineurl.com/2e5bfa',
    //     medio1: 'https://mineurl.com/845320',
    //     dificil1: 'https://mineurl.com/876ae7',
    //     facil2: 'https://mineurl.com/86a28f',
    //     medio2: 'https://mineurl.com/8b4369',
    //     dificil2: 'https://mineurl.com/836b36',
    //     facil3: 'https://mineurl.com/330030',
    //     medio3: 'https://mineurl.com/26db93',
    //     dificil3: 'https://mineurl.com/64360b'
    // },
    // {
    //     nRota: 8,
    //     facil1: 'https://mineurl.com/3db3d0',
    //     medio1: 'https://mineurl.com/ab7903',
    //     dificil1: 'https://mineurl.com/2ca751',
    //     facil2: 'https://mineurl.com/992c98',
    //     medio2: 'https://mineurl.com/cc7a42',
    //     dificil2: 'https://mineurl.com/a73bd2',
    //     facil3: 'https://mineurl.com/3bea67',
    //     medio3: 'https://mineurl.com/2df0bb',
    //     dificil3: 'https://mineurl.com/a73bd2'
    // },
    // {
    //     nRota: 9,
    //     facil1: 'https://mineurl.com/2e5bfa',
    //     medio1: 'https://mineurl.com/845320',
    //     dificil1: 'https://mineurl.com/876ae7',
    //     facil2: 'https://mineurl.com/86a28f',
    //     medio2: 'https://mineurl.com/8b4369',
    //     dificil2: 'https://mineurl.com/836b36',
    //     facil3: 'https://mineurl.com/330030',
    //     medio3: 'https://mineurl.com/26db93',
    //     dificil3: 'https://mineurl.com/64360b'
    // },
    // {
    //     nRota: 10,
    //     facil1: 'https://mineurl.com/342921',
    //     medio1: 'https://mineurl.com/b9d858',
    //     dificil1: 'https://mineurl.com/f860d2',
    //     facil2: 'https://mineurl.com/df1e83',
    //     medio2: 'https://mineurl.com/e0378e',
    //     dificil2: 'https://mineurl.com/b19f3a',
    //     facil3: 'https://mineurl.com/16e49d',
    //     medio3: 'https://mineurl.com/714800',
    //     dificil3: 'https://mineurl.com/5922fe'
    // },
    // {
    //     nRota: 11,
    //     facil1: 'https://mineurl.com/4d8aa7',
    //     medio1: 'https://mineurl.com/6d4fa8',
    //     dificil1: 'https://mineurl.com/99d332',
    //     facil2: 'https://mineurl.com/749f11',
    //     medio2: 'https://mineurl.com/96cf63',
    //     dificil2: 'https://mineurl.com/9eb4ac',
    //     facil3: 'https://mineurl.com/acaec5',
    //     medio3: 'https://mineurl.com/aa7e3d',
    //     dificil3: 'https://mineurl.com/b507b7'
    // },
    // {
    //     nRota: 12,
    //     facil1: 'https://mineurl.com/59a2e8',
    //     medio1: 'https://mineurl.com/420796',
    //     dificil1: 'https://mineurl.com/7aa280',
    //     facil2: 'https://mineurl.com/d3dbd6',
    //     medio2: 'https://mineurl.com/452c34',
    //     dificil2: 'https://mineurl.com/52e696',
    //     facil3: 'https://mineurl.com/61c831',
    //     medio3: 'https://mineurl.com/f29258',
    //     dificil3: 'https://mineurl.com/324564'
    // },
    // {
    //     nRota: 13,
    //     facil1: 'https://mineurl.com/5f57f0',
    //     medio1: 'https://mineurl.com/ebaf0a',
    //     dificil1: 'https://mineurl.com/8ec476',
    //     facil2: 'https://mineurl.com/d3dbd6',
    //     medio2: 'https://mineurl.com/6d8e2c',
    //     dificil2: 'https://mineurl.com/ceaf70',
    //     facil3: 'https://mineurl.com/f47f39',
    //     medio3: 'https://mineurl.com/8f5025',
    //     dificil3: 'https://mineurl.com/eee02e'
    // },
    // {
    //     nRota: 14,
    //     facil1: 'https://mineurl.com/35f55b',
    //     medio1: 'https://mineurl.com/e70a21',
    //     dificil1: 'https://mineurl.com/43ac8f',
    //     facil2: 'https://mineurl.com/e3f6b5',
    //     medio2: 'https://mineurl.com/cbc039',
    //     dificil2: 'https://mineurl.com/eda872',
    //     facil3: 'https://mineurl.com/7a661e',
    //     medio3: 'https://mineurl.com/b7482f',
    //     dificil3: 'https://mineurl.com/f8577c'
    // },
    // {
    //     nRota: 15,
    //     facil1: 'https://mineurl.com/8d52a6',
    //     medio1: 'https://mineurl.com/71db94',
    //     dificil1: 'https://mineurl.com/486032',
    //     facil2: 'https://mineurl.com/b7d45e',
    //     medio2: 'https://mineurl.com/f57211',
    //     dificil2: 'https://mineurl.com/ebb887',
    //     facil3: 'https://mineurl.com/e36cad',
    //     medio3: 'https://mineurl.com/10f02f',
    //     dificil3: 'https://mineurl.com/b461cc'
    // },
    // {
    //     nRota: 16,
    //     facil1: 'https://mineurl.com/35f55b',
    //     medio1: 'https://mineurl.com/cbc039',
    //     dificil1: 'https://mineurl.com/43ac8f',
    //     facil2: 'https://mineurl.com/e3f6b5',
    //     medio2: 'https://mineurl.com/cbc039',
    //     dificil2: 'https://mineurl.com/eda872',
    //     facil3: 'https://mineurl.com/7a661e',
    //     medio3: 'https://mineurl.com/b7482f',
    //     dificil3: 'https://mineurl.com/f8577c'
    // },
    // {
    //     nRota: 17,
    //     facil1: 'https://mineurl.com/f4265c',
    //     medio1: 'https://mineurl.com/632171',
    //     dificil1: 'https://mineurl.com/21a730',
    //     facil2: 'https://mineurl.com/624f8e',
    //     medio2: 'https://mineurl.com/52729d',
    //     dificil2: 'https://mineurl.com/bdb215',
    //     facil3: 'https://mineurl.com/b60ef5',
    //     medio3: 'https://mineurl.com/071df0',
    //     dificil3: 'https://mineurl.com/9689ce'
    // },
    // {
    //     nRota: 18,
    //     facil1: 'https://mineurl.com/0035ee',
    //     medio1: 'https://mineurl.com/2b0de5',
    //     dificil1: 'https://mineurl.com/2ad412',
    //     facil2: 'https://mineurl.com/36d053',
    //     medio2: 'https://mineurl.com/6e273d',
    //     dificil2: 'https://mineurl.com/a4baf5',
    //     facil3: 'https://mineurl.com/196322',
    //     medio3: 'https://mineurl.com/1e0c4a',
    //     dificil3: 'https://mineurl.com/e0996b'
    // },
    // {
    //     nRota: 19,
    //     facil1: 'https://mineurl.com/b759fc',
    //     medio1: 'https://mineurl.com/a4060f',
    //     dificil1: 'https://mineurl.com/c62695',
    //     facil2: 'https://mineurl.com/b0629e',
    //     medio2: 'https://mineurl.com/926650',
    //     dificil2: 'https://mineurl.com/b96e48',
    //     facil3: 'https://mineurl.com/aa29e6',
    //     medio3: 'https://mineurl.com/29a185',
    //     dificil3: 'https://mineurl.com/a806df'
    // },
    // {
    //     nRota: 20,
    //     facil1: 'https://mineurl.com/7768b5',
    //     medio1: 'https://mineurl.com/917f96',
    //     dificil1: 'https://mineurl.com/8b88e5',
    //     facil2: 'https://mineurl.com/dbd374',
    //     medio2: 'https://mineurl.com/9bc92e',
    //     dificil2: 'https://mineurl.com/afd779',
    //     facil3: 'https://mineurl.com/209129',
    //     medio3: 'https://mineurl.com/92e81c',
    //     dificil3: 'https://mineurl.com/23eb81'
    // },
    // {
    //     nRota: 22,
    //     facil1: 'https://mineurl.com/0e5bc1',
    //     medio1: 'https://mineurl.com/70e1b5',
    //     dificil1: 'https://mineurl.com/90830e',
    //     facil2: 'https://mineurl.com/2aba10',
    //     medio2: 'https://mineurl.com/d12cf9',
    //     dificil2: 'https://mineurl.com/525c01',
    //     facil3: 'https://mineurl.com/70f9ff',
    //     medio3: 'https://mineurl.com/4e58b1',
    //     dificil3: 'https://mineurl.com/b8db39'
    // },
    // {
    //     nRota: 21,
    //     facil1: 'https://mineurl.com/c2756c',
    //     medio1: 'https://mineurl.com/c77d40',
    //     dificil1: 'https://mineurl.com/3a1645',
    //     facil2: 'https://mineurl.com/3c3fbc',
    //     medio2: 'https://mineurl.com/bb4c65',
    //     dificil2: 'https://mineurl.com/04a678',
    //     facil3: 'https://mineurl.com/ab8cb6',
    //     medio3: 'https://mineurl.com/944770',
    //     dificil3: 'https://mineurl.com/0104c0'
    // },
    // {
    //     nRota: 23,
    //     facil1: 'https://mineurl.com/b8a750',
    //     medio1: 'https://mineurl.com/f48466',
    //     dificil1: 'https://mineurl.com/a6f9ab',
    //     facil2: 'https://mineurl.com/476a05',
    //     medio2: 'https://mineurl.com/49a8ff',
    //     dificil2: 'https://mineurl.com/111c5f',
    //     facil3: 'https://mineurl.com/ebd144',
    //     medio3: 'https://mineurl.com/687d41',
    //     dificil3: 'https://mineurl.com/f5a6e4'
    // },
    // {
    //     nRota: 24,
    //     facil1: 'https://mineurl.com/e35da7',
    //     medio1: 'https://mineurl.com/8e70db',
    //     dificil1: 'https://mineurl.com/c2f0d2',
    //     facil2: 'https://mineurl.com/897472',
    //     medio2: 'https://mineurl.com/3addac',
    //     dificil2: 'https://mineurl.com/5b6f39',
    //     facil3: 'https://mineurl.com/b0b2a5',
    //     medio3: 'https://mineurl.com/141b52',
    //     dificil3: 'https://mineurl.com/3f77a6'
    // },
    // {
    //     nRota: 25,
    //     facil1: 'https://mineurl.com/5cd051',
    //     medio1: 'https://mineurl.com/342cbc',
    //     dificil1: 'https://mineurl.com/82c315',
    //     facil2: 'https://mineurl.com/192079',
    //     medio2: 'https://mineurl.com/06997e',
    //     dificil2: 'https://mineurl.com/d854d4',
    //     facil3: 'https://mineurl.com/87934d',
    //     medio3: 'https://mineurl.com/054c0f',
    //     dificil3: 'https://mineurl.com/68583e'
    // },
    // {
    //     nRota: 26,
    //     facil1: 'https://mineurl.com/2ead95',
    //     medio1: 'https://mineurl.com/77cc95',
    //     dificil1: 'https://mineurl.com/0351d6',
    //     facil2: 'https://mineurl.com/969f6e',
    //     medio2: 'https://mineurl.com/627e8c',
    //     dificil2: 'https://mineurl.com/360da7',
    //     facil3: 'https://mineurl.com/910fa8',
    //     medio3: 'https://mineurl.com/40e6da',
    //     dificil3: 'https://mineurl.com/f33fcf'
    // },
    // {
    //     nRota: 27,
    //     facil1: 'https://mineurl.com/0a2037',
    //     medio1: 'https://mineurl.com/01244f',
    //     dificil1: 'https://mineurl.com/46cee0',
    //     facil2: 'https://mineurl.com/ab2a29',
    //     medio2: 'https://mineurl.com/2a58e8',
    //     dificil2: 'https://mineurl.com/1af0d4',
    //     facil3: 'https://mineurl.com/35f9d7',
    //     medio3: 'https://mineurl.com/005130',
    //     dificil3: 'https://mineurl.com/c1244e'
    // },
    // {
    //     nRota: 28,
    //     facil1: 'https://mineurl.com/24f4a7',
    //     medio1: 'https://mineurl.com/243587',
    //     dificil1: 'https://mineurl.com/6c4c6d',
    //     facil2: 'https://mineurl.com/56f18d',
    //     medio2: 'https://mineurl.com/deb510',
    //     dificil2: 'https://mineurl.com/b8a1a0',
    //     facil3: 'https://mineurl.com/505552',
    //     medio3: 'https://mineurl.com/198d99',
    //     dificil3: 'https://mineurl.com/e1fd96'
    // },
    // {
    //     nRota: 29,
    //     facil1: 'https://mineurl.com/af323c',
    //     medio1: 'https://mineurl.com/38b1e7',
    //     dificil1: 'https://mineurl.com/e77733',
    //     facil2: 'https://mineurl.com/481327',
    //     medio2: 'https://mineurl.com/90eeb3',
    //     dificil2: 'https://mineurl.com/bfa612',
    //     facil3: 'https://mineurl.com/1ef987',
    //     medio3: 'https://mineurl.com/b62ce9',
    //     dificil3: 'https://mineurl.com/5d192b'
    // },
    // {
    //     nRota: 30,
    //     facil1: 'https://mineurl.com/e26b73',
    //     medio1: 'https://mineurl.com/99c03b',
    //     dificil1: 'https://mineurl.com/5d5e1b',
    //     facil2: 'https://mineurl.com/885d7d',
    //     medio2: 'https://mineurl.com/5efe82',
    //     dificil2: 'https://mineurl.com/e3f5e7',
    //     facil3: 'https://mineurl.com/ed96c0',
    //     medio3: 'https://mineurl.com/3b60fa',
    //     dificil3: 'https://mineurl.com/08a0b9'
    // },
    // {
    //     nRota: 31,
    //     facil1: 'https://mineurl.com/8e9d9f',
    //     medio1: 'https://mineurl.com/acd0f2',
    //     dificil1: 'https://mineurl.com/53f904',
    //     facil2: 'https://mineurl.com/086aa1',
    //     medio2: 'https://mineurl.com/dc9c4c',
    //     dificil2: 'https://mineurl.com/4846f5',
    //     facil3: 'https://mineurl.com/4846f5',
    //     medio3: 'https://mineurl.com/4846f5',
    //     dificil3: 'https://mineurl.com/4846f5'
    // },
    // {
    //     nRota: 32,
    //     facil1: 'https://mineurl.com/828b95',
    //     medio1: 'https://mineurl.com/5c3036',
    //     dificil1: 'https://mineurl.com/13e857',
    //     facil2: 'https://mineurl.com/ab58cf',
    //     medio2: 'https://mineurl.com/5f0ac5',
    //     dificil2: 'https://mineurl.com/1d1f7b',
    //     facil3: 'https://mineurl.com/36bdb8',
    //     medio3: 'https://mineurl.com/67e735',
    //     dificil3: 'https://mineurl.com/9dde92'
    // },
    // {
    //     nRota: 33,
    //     facil1: 'https://mineurl.com/8f75e7',
    //     medio1: 'https://mineurl.com/a1378c',
    //     dificil1: 'https://mineurl.com/429a19',
    //     facil2: 'https://mineurl.com/b1adf7',
    //     medio2: 'https://mineurl.com/b0b2f7',
    //     dificil2: 'https://mineurl.com/d0f14b',
    //     facil3: 'https://mineurl.com/d29dc7',
    //     medio3: 'https://mineurl.com/889dd8',
    //     dificil3: 'https://mineurl.com/0c150e'
    // },
    // {
    //     nRota: 34,
    //     facil1: 'https://mineurl.com/e00f79',
    //     medio1: 'https://mineurl.com/ae58b5',
    //     dificil1: 'https://mineurl.com/78474e',
    //     facil2: 'https://mineurl.com/3e5e22',
    //     medio2: 'https://mineurl.com/2b16ef',
    //     dificil2: 'https://mineurl.com/661271',
    //     facil3: 'https://mineurl.com/84f936',
    //     medio3: 'https://mineurl.com/ace1d6',
    //     dificil3: 'https://mineurl.com/7127a0'
    // },
    // {
    //     nRota: 35,
    //     facil1: 'https://mineurl.com/10e0ba',
    //     medio1: 'https://mineurl.com/7c50c2',
    //     dificil1: 'https://mineurl.com/c2034f',
    //     facil2: 'https://mineurl.com/2b3510',
    //     medio2: 'https://mineurl.com/02c13b',
    //     dificil2: 'https://mineurl.com/34050a',
    //     facil3: 'https://mineurl.com/d58f0b',
    //     medio3: 'https://mineurl.com/34d181',
    //     dificil3: 'https://mineurl.com/34d181'
    // },
    // {
    //     nRota: 36,
    //     facil1: 'https://mineurl.com/e07435',
    //     medio1: 'https://mineurl.com/b93a39',
    //     dificil1: 'https://mineurl.com/c9f3ba',
    //     facil2: 'https://mineurl.com/63f5ef',
    //     medio2: 'https://mineurl.com/46c37b',
    //     dificil2: 'https://mineurl.com/dd8176',
    //     facil3: 'https://mineurl.com/39993e',
    //     medio3: 'https://mineurl.com/cd4d24',
    //     dificil3: 'https://mineurl.com/e5f0f6'
    // },
    // {
    //     nRota: 37,
    //     facil1: 'https://mineurl.com/fd76dd',
    //     medio1: 'https://mineurl.com/99f75b',
    //     dificil1: 'https://mineurl.com/fc08d8',
    //     facil2: 'https://mineurl.com/f033ab',
    //     medio2: 'https://mineurl.com/b40a1f',
    //     dificil2: 'https://mineurl.com/c33521',
    //     facil3: 'https://mineurl.com/7179f8',
    //     medio3: 'https://mineurl.com/520715',
    //     dificil3: 'https://mineurl.com/74d220'
    // },
    // {
    //     nRota: 38,
    //     facil1: 'https://mineurl.com/5d366a',
    //     medio1: 'https://mineurl.com/1bd741',
    //     dificil1: 'https://mineurl.com/592afe',
    //     facil2: 'https://mineurl.com/6caa30',
    //     medio2: 'https://mineurl.com/35038d',
    //     dificil2: 'https://mineurl.com/0c5b81',
    //     facil3: 'https://mineurl.com/ff917e',
    //     medio3: 'https://mineurl.com/b94223',
    //     dificil3: 'https://mineurl.com/01b294'
    // },
    // {
    //     nRota: 39,
    //     facil1: 'https://mineurl.com/2cb16b',
    //     medio1: 'https://mineurl.com/4b917e',
    //     dificil1: 'https://mineurl.com/9b7904',
    //     facil2: 'https://mineurl.com/a5cd7f',
    //     medio2: 'https://mineurl.com/28ff06',
    //     dificil2: 'https://mineurl.com/62f917',
    //     facil3: 'https://mineurl.com/844964',
    //     medio3: 'https://mineurl.com/71751e',
    //     dificil3: 'https://mineurl.com/f2c8f8'
    // },
    // {
    //     nRota: 40,
    //     facil1: 'https://mineurl.com/422c66',
    //     medio1: 'https://mineurl.com/812c3e',
    //     dificil1: 'https://mineurl.com/f8b01b',
    //     facil2: 'https://mineurl.com/73b173',
    //     medio2: 'https://mineurl.com/867bda',
    //     dificil2: 'https://mineurl.com/ff4861',
    //     facil3: 'https://mineurl.com/358cba',
    //     medio3: 'https://mineurl.com/c731e9',
    //     dificil3: 'https://mineurl.com/f1c557'
    // },
    // {
    //     nRota: 41,
    //     facil1: 'https://mineurl.com/ac8e02',
    //     medio1: 'https://mineurl.com/8abda0',
    //     dificil1: 'https://mineurl.com/7b6320',
    //     facil2: 'https://mineurl.com/c908c3',
    //     medio2: 'https://mineurl.com/f80ba5',
    //     dificil2: 'https://mineurl.com/e5f734',
    //     facil3: 'https://mineurl.com/e31282',
    //     medio3: 'https://mineurl.com/927070',
    //     dificil3: 'https://mineurl.com/a30cae'
    // },
    // {
    //     nRota: 42,
    //     facil1: 'https://mineurl.com/98f069',
    //     medio1: 'https://mineurl.com/cc6e71',
    //     dificil1: 'https://mineurl.com/afe455',
    //     facil2: 'https://mineurl.com/750055',
    //     medio2: 'https://mineurl.com/4c35c5',
    //     dificil2: 'https://mineurl.com/13a6a1',
    //     facil3: 'https://mineurl.com/d2d485',
    //     medio3: 'https://mineurl.com/a2dcc7',
    //     dificil3: 'https://mineurl.com/2f89f5'
    // },
    // {
    //     nRota: 43,
    //     facil1: 'https://mineurl.com/84ef03',
    //     medio1: 'https://mineurl.com/4fbb49',
    //     dificil1: 'https://mineurl.com/b3616c',
    //     facil2: 'https://mineurl.com/c4cfd4',
    //     medio2: 'https://mineurl.com/d854ce',
    //     dificil2: 'https://mineurl.com/5b7425',
    //     facil3: 'https://mineurl.com/4a0cad',
    //     medio3: 'https://mineurl.com/85db9a',
    //     dificil3: 'https://mineurl.com/2de5ef'
    // },
    // {
    //     nRota: 44,
    //     facil1: 'https://mineurl.com/3a1596',
    //     medio1: 'https://mineurl.com/719e44',
    //     dificil1: 'https://mineurl.com/4fac23',
    //     facil2: 'https://mineurl.com/ede9bd',
    //     medio2: 'https://mineurl.com/490fb9',
    //     dificil2: 'https://mineurl.com/6bc86a',
    //     facil3: 'https://mineurl.com/c7cfa2',
    //     medio3: 'https://mineurl.com/a5d2c6',
    //     dificil3: 'https://mineurl.com/3ea3bd'
    // },
    // {
    //     nRota: 45,
    //     facil1: 'https://mineurl.com/4e26f5',
    //     medio1: 'https://mineurl.com/47d116',
    //     dificil1: 'https://mineurl.com/4bfd94',
    //     facil2: 'https://mineurl.com/8fad5c',
    //     medio2: 'https://mineurl.com/c9f342',
    //     dificil2: 'https://mineurl.com/bf52f7',
    //     facil3: 'https://mineurl.com/07f58a',
    //     medio3: 'https://mineurl.com/2d4ab3',
    //     dificil3: 'https://mineurl.com/7e408f'
    // },
    // {
    //     nRota: 46,
    //     facil1: 'https://mineurl.com/5f630c',
    //     medio1: 'https://mineurl.com/dbe134',
    //     dificil1: 'https://mineurl.com/407d08',
    //     facil2: 'https://mineurl.com/eef58f',
    //     medio2: 'https://mineurl.com/44d352',
    //     dificil2: 'https://mineurl.com/1bc0cd',
    //     facil3: 'https://mineurl.com/30ccbd',
    //     medio3: 'https://mineurl.com/2ea413',
    //     dificil3: 'https://mineurl.com/527fef'
    // },
    // {
    //     nRota: 47,
    //     facil1: 'https://mineurl.com/32d208',
    //     medio1: 'https://mineurl.com/b3657f',
    //     dificil1: 'https://mineurl.com/81ccb8',
    //     facil2: 'https://mineurl.com/76a47f',
    //     medio2: 'https://mineurl.com/7e634f',
    //     dificil2: 'https://mineurl.com/9ce203',
    //     facil3: 'https://mineurl.com/90cae9',
    //     medio3: 'https://mineurl.com/a47d6c',
    //     dificil3: 'https://mineurl.com/dd8e15'
    // },
    // {
    //     nRota: 48,
    //     facil1: 'https://mineurl.com/cebe7d',
    //     medio1: 'https://mineurl.com/4b1547',
    //     dificil1: 'https://mineurl.com/4e2919',
    //     facil2: 'https://mineurl.com/f0a3e8',
    //     medio2: 'https://mineurl.com/f31e0c',
    //     dificil2: 'https://mineurl.com/5c9f9d',
    //     facil3: 'https://mineurl.com/7e33bd',
    //     medio3: 'https://mineurl.com/072246',
    //     dificil3: 'https://mineurl.com/b838c9'
    // },
    // {
    //     nRota: 49,
    //     facil1: 'https://mineurl.com/0db326',
    //     medio1: 'https://mineurl.com/3fa8b3',
    //     dificil1: 'https://mineurl.com/2c166f',
    //     facil2: 'https://mineurl.com/262e9b',
    //     medio2: 'https://mineurl.com/cfff5c',
    //     dificil2: 'https://mineurl.com/d6e742',
    //     facil3: 'https://mineurl.com/951136',
    //     medio3: 'https://mineurl.com/db0e8c',
    //     dificil3: 'https://mineurl.com/8ff93a'
    // },
    // {
    //     nRota: 50,
    //     facil1: 'https://mineurl.com/6a6bf1',
    //     medio1: 'https://mineurl.com/97c87e',
    //     dificil1: 'https://mineurl.com/25da57',
    //     facil2: 'https://mineurl.com/bf4b1e',
    //     medio2: 'https://mineurl.com/972ccf',
    //     dificil2: 'https://mineurl.com/ce2595',
    //     facil3: 'https://mineurl.com/8bd056',
    //     medio3: 'https://mineurl.com/1bb507',
    //     dificil3: 'https://mineurl.com/41ca19'
    // },
    // {
    //     nRota: 51,
    //     facil1: 'https://mineurl.com/68c99a',
    //     medio1: 'https://mineurl.com/1f3166',
    //     dificil1: 'https://mineurl.com/f4e075',
    //     facil2: 'https://mineurl.com/48d234',
    //     medio2: 'https://mineurl.com/458c6a',
    //     dificil2: 'https://mineurl.com/b123a0',
    //     facil3: 'https://mineurl.com/34033d',
    //     medio3: 'https://mineurl.com/512c44',
    //     dificil3: 'https://mineurl.com/8d4dda'
    // },
    // {
    //     nRota: 52,
    //     facil1: 'https://mineurl.com/8425ee',
    //     medio1: 'https://mineurl.com/27514f',
    //     dificil1: 'https://mineurl.com/3c69b7',
    //     facil2: 'https://mineurl.com/4873d1',
    //     medio2: 'https://mineurl.com/77b4b1',
    //     dificil2: 'https://mineurl.com/917e4d',
    //     facil3: 'https://mineurl.com/7bb75f',
    //     medio3: 'https://mineurl.com/100e32',
    //     dificil3: 'https://mineurl.com/7e022a'
    // },
    // {
    //     nRota: 53,
    //     facil1: 'https://mineurl.com/1e470d',
    //     medio1: 'https://mineurl.com/f5e634',
    //     dificil1: 'https://mineurl.com/3dc0cf',
    //     facil2: 'https://mineurl.com/aaf209',
    //     medio2: 'https://mineurl.com/7b655c',
    //     dificil2: 'https://mineurl.com/dbc7c9',
    //     facil3: 'https://mineurl.com/f938ca',
    //     medio3: 'https://mineurl.com/8ffd97',
    //     dificil3: 'https://mineurl.com/c15bce'
    // },
    // {
    //     nRota: 54,
    //     facil1: 'https://mineurl.com/c0e96c',
    //     medio1: 'https://mineurl.com/01ace5',
    //     dificil1: 'https://mineurl.com/903a62',
    //     facil2: 'https://mineurl.com/32a296',
    //     medio2: 'https://mineurl.com/721d78',
    //     dificil2: 'https://mineurl.com/e9b170',
    //     facil3: 'https://mineurl.com/5cd375',
    //     medio3: 'https://mineurl.com/42567b',
    //     dificil3: 'https://mineurl.com/cf0884'
    // },
    // {
    //     nRota: 55,
    //     facil1: 'https://mineurl.com/11ccb9',
    //     medio1: 'https://mineurl.com/b95ccd',
    //     dificil1: 'https://mineurl.com/a638ed',
    //     facil2: 'https://mineurl.com/045278',
    //     medio2: 'https://mineurl.com/118410',
    //     dificil2: 'https://mineurl.com/9eb2c9',
    //     facil3: 'https://mineurl.com/052c89',
    //     medio3: 'https://mineurl.com/f84470',
    //     dificil3: 'https://mineurl.com/3f3147'
    // },
    // {
    //     nRota: 56,
    //     facil1: 'https://mineurl.com/602595',
    //     medio1: 'https://mineurl.com/7e8249',
    //     dificil1: 'https://mineurl.com/2ca43b',
    //     facil2: 'https://mineurl.com/0bffff',
    //     medio2: 'https://mineurl.com/e83756',
    //     dificil2: 'https://mineurl.com/523d48',
    //     facil3: 'https://mineurl.com/3d7f1e',
    //     medio3: 'https://mineurl.com/67b65f',
    //     dificil3: 'https://mineurl.com/3161da'
    // },
    // {
    //     nRota: 57,
    //     facil1: 'https://mineurl.com/9ee194',
    //     medio1: 'https://mineurl.com/dfa7f1',
    //     dificil1: 'https://mineurl.com/a10e9e',
    //     facil2: 'https://mineurl.com/98b1a6',
    //     medio2: 'https://mineurl.com/1c2c61',
    //     dificil2: 'https://mineurl.com/01e7d2',
    //     facil3: 'https://mineurl.com/5e07a6',
    //     medio3: 'https://mineurl.com/41b95b',
    //     dificil3: 'https://mineurl.com/732955'
    // },
    // {
    //     nRota: 58,
    //     facil1: 'https://mineurl.com/f0a1f1',
    //     medio1: 'https://mineurl.com/0b1ea5',
    //     dificil1: 'https://mineurl.com/21f68f',
    //     facil2: 'https://mineurl.com/a94f81',
    //     medio2: 'https://mineurl.com/0c6237',
    //     dificil2: 'https://mineurl.com/9cee1b',
    //     facil3: 'https://mineurl.com/c2eb82',
    //     medio3: 'https://mineurl.com/f745c2',
    //     dificil3: 'https://mineurl.com/a003d0'
    // },
    // {
    //     nRota: 59,
    //     facil1: 'https://mineurl.com/c565ac',
    //     medio1: 'https://mineurl.com/6c28a9',
    //     dificil1: 'https://mineurl.com/f930cb',
    //     facil2: 'https://mineurl.com/e13b0e',
    //     medio2: 'https://mineurl.com/3b1b09',
    //     dificil2: 'https://mineurl.com/3a60b4',
    //     facil3: 'https://mineurl.com/78e87f',
    //     medio3: 'https://mineurl.com/aaee3d',
    //     dificil3: 'https://mineurl.com/dd89f0'
    // },
    // {
    //     nRota: 60,
    //     facil1: 'https://mineurl.com/0800be',
    //     medio1: 'https://mineurl.com/2f3199',
    //     dificil1: 'https://mineurl.com/4f39c4',
    //     facil2: 'https://mineurl.com/4137e3',
    //     medio2: 'https://mineurl.com/c62e95',
    //     dificil2: 'https://mineurl.com/3969fc',
    //     facil3: 'https://mineurl.com/3969fc',
    //     medio3: 'https://mineurl.com/3969fc',
    //     dificil3: 'https://mineurl.com/3969fc'
    // }
    {
        nRota: 61,
        facil1: 'https://mineurl.com/55c7c9',
        medio1: 'https://mineurl.com/32c510',
        dificil1: 'https://mineurl.com/a6077e',
        facil2: 'https://mineurl.com/a57610',
        medio2: 'https://mineurl.com/43a212',
        dificil2: 'https://mineurl.com/389feb',
        facil3: 'https://mineurl.com/b82968',
        medio3: 'https://mineurl.com/54a6df',
        dificil3: 'https://mineurl.com/cbe07f'
    },
    {
        nRota: 62,
        facil1: 'https://mineurl.com/6a4f69',
        medio1: 'https://mineurl.com/7ba734',
        dificil1: 'https://mineurl.com/262e43',
        facil2: 'https://mineurl.com/a7260f',
        medio2: 'https://mineurl.com/f78f43',
        dificil2: 'https://mineurl.com/c9be5d',
        facil3: 'https://mineurl.com/0ca285',
        medio3: 'https://mineurl.com/0667fa',
        dificil3: 'https://mineurl.com/e915e5'
    },
    {
        nRota: 63,
        facil1: 'https://mineurl.com/0c8b6d',
        medio1: 'https://mineurl.com/6e5d7f',
        dificil1: 'https://mineurl.com/706ea2',
        facil2: 'https://mineurl.com/4ece20',
        medio2: 'https://mineurl.com/89f6e6',
        dificil2: 'https://mineurl.com/c7a4b8',
        facil3: 'https://mineurl.com/1e82fa',
        medio3: 'https://mineurl.com/6dd1c8',
        dificil3: 'https://mineurl.com/4706db'
    },
    {
        nRota: 64,
        facil1: 'https://mineurl.com/0fd120',
        medio1: 'https://mineurl.com/1067a9',
        dificil1: 'https://mineurl.com/c442b3',
        facil2: 'https://mineurl.com/c8cb97',
        medio2: 'https://mineurl.com/c57fbd',
        dificil2: 'https://mineurl.com/b54374',
        facil3: 'https://mineurl.com/4772de',
        medio3: 'https://mineurl.com/b8aa3b',
        dificil3: 'https://mineurl.com/d10f99'
    },
    {
        nRota: 65,
        facil1: 'https://mineurl.com/f142e3',
        medio1: 'https://mineurl.com/b948b6',
        dificil1: 'https://mineurl.com/924874',
        facil2: 'https://mineurl.com/b43ea7',
        medio2: 'https://mineurl.com/698867',
        dificil2: 'https://mineurl.com/0f2d82',
        facil3: 'https://mineurl.com/54caa4',
        medio3: 'https://mineurl.com/596e28',
        dificil3: 'https://mineurl.com/65a6c5'
    },
    {
        nRota: 66,
        facil1: 'https://mineurl.com/f1e4d2',
        medio1: 'https://mineurl.com/e75727',
        dificil1: 'https://mineurl.com/eecf4e',
        facil2: 'https://mineurl.com/4aa8e2',
        medio2: 'https://mineurl.com/21c00d',
        dificil2: 'https://mineurl.com/c99c34',
        facil3: 'https://mineurl.com/3d4bd3',
        medio3: 'https://mineurl.com/26881d',
        dificil3: 'https://mineurl.com/8b09ae'
    },
    {
        nRota: 67,
        facil1: 'https://mineurl.com/a5876e',
        medio1: 'https://mineurl.com/88cda4',
        dificil1: 'https://mineurl.com/17e679',
        facil2: 'https://mineurl.com/40bc7e',
        medio2: 'https://mineurl.com/8ad710',
        dificil2: 'https://mineurl.com/a92fc3',
        facil3: 'https://mineurl.com/c34c9f',
        medio3: 'https://mineurl.com/99ce2f',
        dificil3: 'https://mineurl.com/de9b4a'
    },
    {
        nRota: 68,
        facil1: 'https://mineurl.com/914e81',
        medio1: 'https://mineurl.com/a5f691',
        dificil1: 'https://mineurl.com/ad8be1',
        facil2: 'https://mineurl.com/9599cb',
        medio2: 'https://mineurl.com/54fcdb',
        dificil2: 'https://mineurl.com/175110',
        facil3: 'https://mineurl.com/f34604',
        medio3: 'https://mineurl.com/4668e1',
        dificil3: 'https://mineurl.com/70a4fc'
    },
    {
        nRota: 69,
        facil1: 'https://mineurl.com/c751d9',
        medio1: 'https://mineurl.com/8637cd',
        dificil1: 'https://mineurl.com/8d4393',
        facil2: 'https://mineurl.com/86751e',
        medio2: 'https://mineurl.com/ec3889',
        dificil2: 'https://mineurl.com/36031b',
        facil3: 'https://mineurl.com/f7333b',
        medio3: 'https://mineurl.com/589e9f',
        dificil3: 'https://mineurl.com/3a3ff6'
    },
    {
        nRota: 70,
        facil1: 'https://mineurl.com/fe057d',
        medio1: 'https://mineurl.com/a4d0eb',
        dificil1: 'https://mineurl.com/ee7ecc',
        facil2: 'https://mineurl.com/3c5b01',
        medio2: 'https://mineurl.com/b48e2f',
        dificil2: 'https://mineurl.com/ae8a37',
        facil3: 'https://mineurl.com/59e7b5',
        medio3: 'https://mineurl.com/30eb60',
        dificil3: 'https://mineurl.com/5fd963'
    },
    {
        nRota: 71,
        facil1: 'https://mineurl.com/a09142',
        medio1: 'https://mineurl.com/616739',
        dificil1: 'https://mineurl.com/c292d9',
        facil2: 'https://mineurl.com/e8af80',
        medio2: 'https://mineurl.com/369b0f',
        dificil2: 'https://mineurl.com/8c417a',
        facil3: 'https://mineurl.com/747c3d',
        medio3: 'https://mineurl.com/fd1ea2',
        dificil3: 'https://mineurl.com/d14a43'
    },
    {
        nRota: 72,
        facil1: 'https://mineurl.com/a742e3',
        medio1: 'https://mineurl.com/eb0c69',
        dificil1: 'https://mineurl.com/73553d',
        facil2: 'https://mineurl.com/19bd09',
        medio2: 'https://mineurl.com/f59f5b',
        dificil2: 'https://mineurl.com/0452ce',
        facil3: 'https://mineurl.com/7b738c',
        medio3: 'https://mineurl.com/9554a7',
        dificil3: 'https://mineurl.com/c5e2fd'
    },
    {
        nRota: 73,
        facil1: 'https://mineurl.com/37a604',
        medio1: 'https://mineurl.com/d84c01',
        dificil1: 'https://mineurl.com/d6328e',
        facil2: 'https://mineurl.com/11528b',
        medio2: 'https://mineurl.com/f446e8',
        dificil2: 'https://mineurl.com/b5a7ba',
        facil3: 'https://mineurl.com/dd338d',
        medio3: 'https://mineurl.com/1e48c4',
        dificil3: 'https://mineurl.com/c72a51'
    },
    {
        nRota: 74,
        facil1: 'https://mineurl.com/97f3fd',
        medio1: 'https://mineurl.com/32032d',
        dificil1: 'https://mineurl.com/caac5e',
        facil2: 'https://mineurl.com/b7cc96',
        medio2: 'https://mineurl.com/f092a3',
        dificil2: 'https://mineurl.com/12bb04',
        facil3: 'https://mineurl.com/12ac88',
        medio3: 'https://mineurl.com/bdbc33',
        dificil3: 'https://mineurl.com/739c74'
    },
    {
        nRota: 75,
        facil1: 'https://mineurl.com/fbb761',
        medio1: 'https://mineurl.com/673604',
        dificil1: 'https://mineurl.com/d4602b',
        facil2: 'https://mineurl.com/e63a74',
        medio2: 'https://mineurl.com/8efc08',
        dificil2: 'https://mineurl.com/e040e0',
        facil3: 'https://mineurl.com/1fa04c',
        medio3: 'https://mineurl.com/f3d264',
        dificil3: 'https://mineurl.com/d1e33b'
    },
    {
        nRota: 76,
        facil1: 'https://mineurl.com/657820',
        medio1: 'https://mineurl.com/500818',
        dificil1: 'https://mineurl.com/b0b7b2',
        facil2: 'https://mineurl.com/84334c',
        medio2: 'https://mineurl.com/43acac',
        dificil2: 'https://mineurl.com/4fe816',
        facil3: 'https://mineurl.com/386a05',
        medio3: 'https://mineurl.com/a38fe5',
        dificil3: 'https://mineurl.com/1fc905'
    },
    {
        nRota: 77,
        facil1: 'https://mineurl.com/8dbd13',
        medio1: 'https://mineurl.com/1c7dbc',
        dificil1: 'https://mineurl.com/e30fb7',
        facil2: 'https://mineurl.com/4b202a',
        medio2: 'https://mineurl.com/c11a94',
        dificil2: 'https://mineurl.com/ec5037',
        facil3: 'https://mineurl.com/dfe570',
        medio3: 'https://mineurl.com/591f6f',
        dificil3: 'https://mineurl.com/f48b84'
    },
    {
        nRota: 78,
        facil1: 'https://mineurl.com/17f316',
        medio1: 'https://mineurl.com/1b6fda',
        dificil1: 'https://mineurl.com/cdd52a',
        facil2: 'https://mineurl.com/576f23',
        medio2: 'https://mineurl.com/cd1474',
        dificil2: 'https://mineurl.com/16c862',
        facil3: 'https://mineurl.com/a1d820',
        medio3: 'https://mineurl.com/1a0cf8',
        dificil3: 'https://mineurl.com/b0f4b7'
    },
    {
        nRota: 79,
        facil1: 'https://mineurl.com/0bc438',
        medio1: 'https://mineurl.com/d6dfab',
        dificil1: 'https://mineurl.com/6adeeb',
        facil2: 'https://mineurl.com/485bcd',
        medio2: 'https://mineurl.com/cb92a9',
        dificil2: 'https://mineurl.com/6e1639',
        facil3: 'https://mineurl.com/e3448c',
        medio3: 'https://mineurl.com/b64ace',
        dificil3: 'https://mineurl.com/3eb058'
    },
    {
        nRota: 80,
        facil1: 'https://mineurl.com/e8cca8',
        medio1: 'https://mineurl.com/02bd06',
        dificil1: 'https://mineurl.com/c6f116',
        facil2: 'https://mineurl.com/f32cf1',
        medio2: 'https://mineurl.com/f5ea51',
        dificil2: 'https://mineurl.com/3704de',
        facil3: 'https://mineurl.com/4126f1',
        medio3: 'https://mineurl.com/5a4c04',
        dificil3: 'https://mineurl.com/c86627'
    },
    {
        nRota: 81,
        facil1: 'https://mineurl.com/9ed9cf',
        medio1: 'https://mineurl.com/880774',
        dificil1: 'https://mineurl.com/0fd2f2',
        facil2: 'https://mineurl.com/282787',
        medio2: 'https://mineurl.com/7da20d',
        dificil2: 'https://mineurl.com/b2cd8d',
        facil3: 'https://mineurl.com/ce2150',
        medio3: 'https://mineurl.com/21bc85',
        dificil3: 'https://mineurl.com/fda4c3'
    },
    {
        nRota: 82,
        facil1: 'https://mineurl.com/80397e',
        medio1: 'https://mineurl.com/3fdcac',
        dificil1: 'https://mineurl.com/5d3e37',
        facil2: 'https://mineurl.com/65eb67',
        medio2: 'https://mineurl.com/a19d4d',
        dificil2: 'https://mineurl.com/52a4ab',
        facil3: 'https://mineurl.com/73b99c',
        medio3: 'https://mineurl.com/276134',
        dificil3: 'https://mineurl.com/fcb357'
    },
    {
        nRota: 83,
        facil1: 'https://mineurl.com/48d744',
        medio1: 'https://mineurl.com/70459d',
        dificil1: 'https://mineurl.com/dd9004',
        facil2: 'https://mineurl.com/9c78e8',
        medio2: 'https://mineurl.com/b4ad24',
        dificil2: 'https://mineurl.com/71738a',
        facil3: 'https://mineurl.com/36d9be',
        medio3: 'https://mineurl.com/b8a3b0',
        dificil3: 'https://mineurl.com/897529'
    },
    {
        nRota: 84,
        facil1: 'https://mineurl.com/6a19f0',
        medio1: 'https://mineurl.com/c25f46',
        dificil1: 'https://mineurl.com/980f8a',
        facil2: 'https://mineurl.com/1b19b6',
        medio2: 'https://mineurl.com/3be010',
        dificil2: 'https://mineurl.com/0be95c',
        facil3: 'https://mineurl.com/a05900',
        medio3: 'https://mineurl.com/e36a44',
        dificil3: 'https://mineurl.com/ea4fc6'
    },
    {
        nRota: 85,
        facil1: 'https://mineurl.com/cc271d',
        medio1: 'https://mineurl.com/b93d00',
        dificil1: 'https://mineurl.com/f38419',
        facil2: 'https://mineurl.com/6536cf',
        medio2: 'https://mineurl.com/8d40b1',
        dificil2: 'https://mineurl.com/c055fc',
        facil3: 'https://mineurl.com/13417d',
        medio3: 'https://mineurl.com/8947ac',
        dificil3: 'https://mineurl.com/3c7542'
    },
    {
        nRota: 86,
        facil1: 'https://mineurl.com/8ee713',
        medio1: 'https://mineurl.com/403fde',
        dificil1: 'https://mineurl.com/fa5768',
        facil2: 'https://mineurl.com/29a40e',
        medio2: 'https://mineurl.com/ab0be6',
        dificil2: 'https://mineurl.com/24bc96',
        facil3: 'https://mineurl.com/b3923e',
        medio3: 'https://mineurl.com/aaad6f',
        dificil3: 'https://mineurl.com/3c9aa8'
    },
    {
        nRota: 87,
        facil1: 'https://mineurl.com/0a42ce',
        medio1: 'https://mineurl.com/e4b2ce',
        dificil1: 'https://mineurl.com/331b29',
        facil2: 'https://mineurl.com/c7dd09',
        medio2: 'https://mineurl.com/ac10c8',
        dificil2: 'https://mineurl.com/49c3df',
        facil3: 'https://mineurl.com/ee134c',
        medio3: 'https://mineurl.com/75667e',
        dificil3: 'https://mineurl.com/77f599'
    },
    {
        nRota: 88,
        facil1: 'https://mineurl.com/3f9e04',
        medio1: 'https://mineurl.com/7a666c',
        dificil1: 'https://mineurl.com/5a4d73',
        facil2: 'https://mineurl.com/539135',
        medio2: 'https://mineurl.com/9a5721',
        dificil2: 'https://mineurl.com/5db495',
        facil3: 'https://mineurl.com/1765be',
        medio3: 'https://mineurl.com/319273',
        dificil3: 'https://mineurl.com/7c49bc'
    },
    {
        nRota: 89,
        facil1: 'https://mineurl.com/785ac6',
        medio1: 'https://mineurl.com/77dfa6',
        dificil1: 'https://mineurl.com/abcf4c',
        facil2: 'https://mineurl.com/e71144',
        medio2: 'https://mineurl.com/67746a',
        dificil2: 'https://mineurl.com/5a94c1',
        facil3: 'https://mineurl.com/415c7d',
        medio3: 'https://mineurl.com/05a9c9',
        dificil3: 'https://mineurl.com/b8280f'
    },
    {
        nRota: 90,
        facil1: 'https://mineurl.com/2448cc',
        medio1: 'https://mineurl.com/cd354f',
        dificil1: 'https://mineurl.com/46069a',
        facil2: 'https://mineurl.com/152961',
        medio2: 'https://mineurl.com/1a2d66',
        dificil2: 'https://mineurl.com/5ef73e',
        facil3: 'https://mineurl.com/2adba8',
        medio3: 'https://mineurl.com/c2e2d4',
        dificil3: 'https://mineurl.com/2393dd'
    },
    {
        nRota: 91,
        facil1: 'https://mineurl.com/f9326f',
        medio1: 'https://mineurl.com/c32ab2',
        dificil1: 'https://mineurl.com/6e4410',
        facil2: 'https://mineurl.com/358ac5',
        medio2: 'https://mineurl.com/06805d',
        dificil2: 'https://mineurl.com/e40ab1',
        facil3: 'https://mineurl.com/8d08cb',
        medio3: 'https://mineurl.com/d19334',
        dificil3: 'https://mineurl.com/7538e1'
    },
    {
        nRota: 92,
        facil1: 'https://mineurl.com/5c3397',
        medio1: 'https://mineurl.com/250e1d',
        dificil1: 'https://mineurl.com/0d5867',
        facil2: 'https://mineurl.com/2c6af3',
        medio2: 'https://mineurl.com/4ab8f1',
        dificil2: 'https://mineurl.com/5c04ea',
        facil3: 'https://mineurl.com/086c5c',
        medio3: 'https://mineurl.com/e41e6e',
        dificil3: 'https://mineurl.com/330fdd'
    },
    {
        nRota: 93,
        facil1: 'https://mineurl.com/04e44d',
        medio1: 'https://mineurl.com/e4968f',
        dificil1: 'https://mineurl.com/cfc437',
        facil2: 'https://mineurl.com/6372ca',
        medio2: 'https://mineurl.com/7832f4',
        dificil2: 'https://mineurl.com/58fb6a',
        facil3: 'https://mineurl.com/078f90',
        medio3: 'https://mineurl.com/eb5d1e',
        dificil3: 'https://mineurl.com/f5bb86'
    },
    {
        nRota: 94,
        facil1: 'https://mineurl.com/1876e9',
        medio1: 'https://mineurl.com/587eab',
        dificil1: 'https://mineurl.com/03fc71',
        facil2: 'https://mineurl.com/3f30a0',
        medio2: 'https://mineurl.com/9e7a86',
        dificil2: 'https://mineurl.com/dd52f1',
        facil3: 'https://mineurl.com/915852',
        medio3: 'https://mineurl.com/28d6e4',
        dificil3: 'https://mineurl.com/936ca4'
    },
    {
        nRota: 95,
        facil1: 'https://mineurl.com/5873bd',
        medio1: 'https://mineurl.com/094528',
        dificil1: 'https://mineurl.com/e753d8',
        facil2: 'https://mineurl.com/aa3b23',
        medio2: 'https://mineurl.com/4c4109',
        dificil2: 'https://mineurl.com/95cbcc',
        facil3: 'https://mineurl.com/8d2819',
        medio3: 'https://mineurl.com/3a624c',
        dificil3: 'https://mineurl.com/0c972a'
    },
    {
        nRota: 96,
        facil1: 'https://mineurl.com/f89ca5',
        medio1: 'https://mineurl.com/488581',
        dificil1: 'https://mineurl.com/b0a70d',
        facil2: 'https://mineurl.com/b0abe3',
        medio2: 'https://mineurl.com/5fed6f',
        dificil2: 'https://mineurl.com/506a89',
        facil3: 'https://mineurl.com/bc5825',
        medio3: 'https://mineurl.com/f19c77',
        dificil3: 'https://mineurl.com/ed5a2b'
    },
    {
        nRota: 97,
        facil1: 'https://mineurl.com/2c5145',
        medio1: 'https://mineurl.com/e9e873',
        dificil1: 'https://mineurl.com/b238d7',
        facil2: 'https://mineurl.com/26f7c1',
        medio2: 'https://mineurl.com/31bd07',
        dificil2: 'https://mineurl.com/9a802e',
        facil3: 'https://mineurl.com/115a20',
        medio3: 'https://mineurl.com/1c3745',
        dificil3: 'https://mineurl.com/5c8763'
    },
    {
        nRota: 98,
        facil1: 'https://mineurl.com/5d3730',
        medio1: 'https://mineurl.com/8d3143',
        dificil1: 'https://mineurl.com/f3d49a',
        facil2: 'https://mineurl.com/9cf7a9',
        medio2: 'https://mineurl.com/d995e4',
        dificil2: 'https://mineurl.com/50ffce',
        facil3: 'https://mineurl.com/b41def',
        medio3: 'https://mineurl.com/40792a',
        dificil3: 'https://mineurl.com/f6e90f'
    },
    {
        nRota: 99,
        facil1: 'https://mineurl.com/f7130d',
        medio1: 'https://mineurl.com/7eb162',
        dificil1: 'https://mineurl.com/b1a633',
        facil2: 'https://mineurl.com/3adc38',
        medio2: 'https://mineurl.com/26794a',
        dificil2: 'https://mineurl.com/8397bb',
        facil3: 'https://mineurl.com/c33cc3',
        medio3: 'https://mineurl.com/8eb00e',
        dificil3: 'https://mineurl.com/4bfc04'
    },
    {
        nRota: 100,
        facil1: 'https://mineurl.com/c60c9b',
        medio1: 'https://mineurl.com/7db79c',
        dificil1: 'https://mineurl.com/db4ae7',
        facil2: 'https://mineurl.com/0a7876',
        medio2: 'https://mineurl.com/403b7b',
        dificil2: 'https://mineurl.com/5a8cfb',
        facil3: 'https://mineurl.com/acb834',
        medio3: 'https://mineurl.com/bcedac',
        dificil3: 'https://mineurl.com/0363fc'
    }
]

module.exports = links